apiVersion: apps/v1
kind: Deployment
metadata:
  name: drogon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drogon-app
  template:
    metadata:
      labels:
        app: drogon-app
    spec:
      containers:
      - name: drogon-container
        image: zikker1/drogonapi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: drogon-service
spec:
  type: NodePort
  selector:
    app: drogon-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30007